config/routes.rb
Mni::Application.routes.draw do
  resources :membros

  resources :grupos

end

app/models/grupo.rb
class Grupo < ActiveRecord::Base

  has_many :membros

end

app/models/membro.rb
class Membro < ActiveRecord::Base

belongs_to :grupo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  # GET /grupos
  # GET /grupos.xml
  def index
    @grupos = Grupo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @grupos }
    end
  end

  # GET /grupos/1
  # GET /grupos/1.xml
  def show
    @grupo = Grupo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @grupo }
    end
  end

  # GET /grupos/new
  # GET /grupos/new.xml
  def new
    @grupo = Grupo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @grupo }
    end
  end

  # GET /grupos/1/edit
  def edit
    @grupo = Grupo.find(params[:id])
  end

  # POST /grupos
  # POST /grupos.xml
  def create
    @grupo = Grupo.new(params[:grupo])

    respond_to do |format|
      if @grupo.save
        format.html { redirect_to(@grupo, :notice => 'Grupo was successfully created.') }
        format.xml  { render :xml => @grupo, :status => :created, :location => @grupo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @grupo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /grupos/1
  # PUT /grupos/1.xml
  def update
    @grupo = Grupo.find(params[:id])

    respond_to do |format|
      if @grupo.update_attributes(params[:grupo])
        format.html { redirect_to(@grupo, :notice => 'Grupo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @grupo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /grupos/1
  # DELETE /grupos/1.xml
  def destroy
    @grupo = Grupo.find(params[:id])
    @grupo.destroy

    respond_to do |format|
      format.html { redirect_to(grupos_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/membros_controller.rb
class MembrosController < ApplicationController
  # GET /membros
  # GET /membros.xml
  def index
    @membros = Membro.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @membros }
    end
  end

  # GET /membros/1
  # GET /membros/1.xml
  def show
    @membro = Membro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @membro }
    end
  end

  # GET /membros/new
  # GET /membros/new.xml
  def new
    @membro = Membro.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @membro }
    end
  end

  # GET /membros/1/edit
  def edit
    @membro = Membro.find(params[:id])
  end

  # POST /membros
  # POST /membros.xml
  def create
    @membro = Membro.new(params[:membro])

    respond_to do |format|
      if @membro.save
        format.html { redirect_to(@membro, :notice => 'Membro was successfully created.') }
        format.xml  { render :xml => @membro, :status => :created, :location => @membro }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @membro.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /membros/1
  # PUT /membros/1.xml
  def update
    @membro = Membro.find(params[:id])

    respond_to do |format|
      if @membro.update_attributes(params[:membro])
        format.html { redirect_to(@membro, :notice => 'Membro was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @membro.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /membros/1
  # DELETE /membros/1.xml
  def destroy
    @membro = Membro.find(params[:id])
    @membro.destroy

    respond_to do |format|
      format.html { redirect_to(membros_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/membros_helper.rb
module MembrosHelper
end

app/views/grupos/_form.html.erb
<%= form_for(@grupo) do |f| %>
  <% if @grupo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grupo.errors.count, "error") %> prohibited this grupo from being saved:</h2>

      <ul>
      <% @grupo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grupos/edit.html.erb
<h1>Editing grupo</h1>

<%= render 'form' %>

<%= link_to 'Show', @grupo %> |
<%= link_to 'Back', grupos_path %>

app/views/grupos/index.html.erb
<h1>Listing grupos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @grupos.each do |grupo| %>
  <tr>
    <td><%= grupo.nome %></td>
    <td><%= link_to 'Show', grupo %></td>
    <td><%= link_to 'Edit', edit_grupo_path(grupo) %></td>
    <td><%= link_to 'Destroy', grupo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Grupo', new_grupo_path %>

app/views/grupos/new.html.erb
<h1>New grupo</h1>

<%= render 'form' %>

<%= link_to 'Back', grupos_path %>

app/views/grupos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @grupo.nome %>
</p>


<%= link_to 'Edit', edit_grupo_path(@grupo) %> |
<%= link_to 'Back', grupos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mni</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/membros/_form.html.erb
<%= form_for(@membro) do |f| %>
  <% if @membro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membro.errors.count, "error") %> prohibited this membro from being saved:</h2>

      <ul>
      <% @membro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :grupo_id %><br />
    <%= f.text_field :grupo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/membros/edit.html.erb
<h1>Editing membro</h1>

<%= render 'form' %>

<%= link_to 'Show', @membro %> |
<%= link_to 'Back', membros_path %>

app/views/membros/index.html.erb
<h1>Listing membros</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Telefone</th>
    <th>Email</th>
    <th>Grupo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @membros.each do |membro| %>
  <tr>
    <td><%= membro.nome %></td>
    <td><%= membro.telefone %></td>
    <td><%= membro.email %></td>
    <td><%= membro.grupo_id %></td>
    <td><%= link_to 'Show', membro %></td>
    <td><%= link_to 'Edit', edit_membro_path(membro) %></td>
    <td><%= link_to 'Destroy', membro, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Membro', new_membro_path %>

app/views/membros/new.html.erb
<h1>New membro</h1>

<%= render 'form' %>

<%= link_to 'Back', membros_path %>

app/views/membros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @membro.nome %>
</p>

<p>
  <b>Telefone:</b>
  <%= @membro.telefone %>
</p>

<p>
  <b>Email:</b>
  <%= @membro.email %>
</p>
<p>
  <b>Grupo:</b>
  <%= @membro.grupo_id %>
</p>


<%= link_to 'Edit', edit_membro_path(@membro) %> |
<%= link_to 'Back', membros_path %>